version: '3.3'

services:
    django:
        build: ./django
        image: custom_django
        container_name: django_sample
        ports:
            - "8780:8780"
        volumes:
            - ./src:/code
        restart: always
