version: '3.7'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8780:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"
        links:
            - django
        depends_on:
            - django

    mysql:
        image: jsurf/rpi-mariadb   # MariaDBになっているけど気にしない
        container_name: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: django_db
            MYSQL_USER: django
            MYSQL_PASSWORD: user_password
            TZ: "Asia/Tokyo"
        volumes:
            - database:/var/lib/mysql
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"
        expose:
            - "3306"

    django:
        build: ./django
        image: custom_django
        container_name: django
        environment:
            DATABASE_HOST: mysql              # docker-compose上における、mysqlのサービス名を指定
            DATABASE_PORT: 3306               # mysqlで利用するポートを指定
            DATABASE_DBNAME: django_db        # mysqlのdatabase名を指定
            DATABASE_USER: django             # mysqlのuser名を指定
            DATABASE_PASSWORD: user_password  # mysqlのuser名のパスワードを指定
            DATABASE_CHARSET: utf8mb4         # 文字コードの指定
        volumes:
            - ./django/uwsgi.ini:/uwsgi.ini:ro
            - ./django/src:/code
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"
        expose:
            - "8081"
        links:
            - mysql
        depends_on:
            - mysql

volumes:
    database:
