version: '3.3'

services:
    flask:
        build: ./flask
        image: custom_flask
        container_name: flask
        ports:
            - "8780:8780"
        volumes:
            - ./app:/app
        restart: always
